//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class datacenterEntities : DbContext
    {
        public datacenterEntities()
            : base("name=datacenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<areas> areas { get; set; }
        public DbSet<cosas_requi> cosas_requi { get; set; }
        public DbSet<lugares> lugares { get; set; }
        public DbSet<requerimientos> requerimientos { get; set; }
        public DbSet<sigi_contador_folios> sigi_contador_folios { get; set; }
        public DbSet<sigi_documentos> sigi_documentos { get; set; }
        public DbSet<sigi_oficios> sigi_oficios { get; set; }
        public DbSet<sigi_oficios_documentos_recepcion> sigi_oficios_documentos_recepcion { get; set; }
        public DbSet<sigi_reportes_param> sigi_reportes_param { get; set; }
        public DbSet<solicitudes> solicitudes { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
