//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class requerimientos
    {
        public int id { get; set; }
        public string lista_area_11 { get; set; }
        public string lista_area_10 { get; set; }
        public string lista_area_6 { get; set; }
        public int estado { get; set; }
        public int id_ref { get; set; }
    }
}
