//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sigi_oficios_documentos_recepcion
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int id_oficio { get; set; }
        public int id_documentos { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> ccp { get; set; }
        public Nullable<System.DateTime> fecha_visto { get; set; }
        public string estatus_inicial { get; set; }
        public string estatus_final { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
