//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sigi_oficios
    {
        public int id { get; set; }
        public string tipo_oficio { get; set; }
        public string folio { get; set; }
        public string folio_institucion { get; set; }
        public string origen { get; set; }
        public Nullable<int> id_usuario_emisor { get; set; }
        public string nombre_emisor { get; set; }
        public string institucion_emisor { get; set; }
        public string cargo { get; set; }
        public string asunto_emisor { get; set; }
        public string asunto_receptor { get; set; }
        public Nullable<bool> respuesta { get; set; }
        public Nullable<int> respondido { get; set; }
        public string destino { get; set; }
        public Nullable<int> vinculado { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<System.TimeSpan> hora_recepcion { get; set; }
        public string comentarios { get; set; }
        public System.DateTime created_at { get; set; }
        public int created_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public int updated_by { get; set; }
    }
}
