//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudes
    {
        public int id { get; set; }
        public string imagen { get; set; }
        public string nombre_evento { get; set; }
        public string lugar_evento { get; set; }
        public System.DateTime fecha_evento { get; set; }
        public System.DateTime fecha_evento_fin { get; set; }
        public System.TimeSpan hora_evento_ini { get; set; }
        public System.TimeSpan hora_evento_fin { get; set; }
        public string area_evento { get; set; }
        public int usuario_solicita { get; set; }
        public System.DateTime fecha_soliciud { get; set; }
        public string color_fondo { get; set; }
        public string color_texto { get; set; }
        public int tipo_agenda { get; set; }
        public string ediciones { get; set; }
        public int publica { get; set; }
        public int estado { get; set; }
    }
}
