//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_local
    {
        public int Id { get; set; }
        public string nombre_formal { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string contrasena { get; set; }
        public string correo { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> privilegios { get; set; }
        public Nullable<int> priv_sigi { get; set; }
        public Nullable<int> priv_siu { get; set; }
        public Nullable<int> priv_sia { get; set; }
        public Nullable<int> titular { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
